package DAO;

/**
 * Implementing this interface allows generate and verify combination in game
 */
public interface Combination {
    /**
     * For generating the combination
     * @return array of combination as int
     */
    int[] generate();

    /**
     * For verification of combinations
     * @param compComb array of int with combination generated by computer
     * @param userComb array of int with combination entered by user
     * @return String with result of verification
     */
    String verify(int[] compComb,int[] userComb);
}
